language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAWGUPMT3JWO3X2OEK
  secret_access_key:
    secure: E27nQKzhpg01AulpwvAw4e1JeuUbo9nmKWo/d5k3rJHx0ePdCGEpIFrgxfAC/k1nCGFvdA/EP28UzlG9QK0qQLOsUY66UwLXAqnJJANvWqO4XVo9PeYQXb57q+jKX+aWkdIJIwzznb2K2GQgo3hvE6g7B5p2QXWOlB55pS7RjdJdV00J1PY36YlJy2JqqHsYn2Ssj3c13qa1b4Qkr0wQ2Kc99fki8w+HPSocJ1WatU7Q54mLmE35FXnm9q23JLsy3wTCWLDcjiUstdQqBxiXvAED+Xhap7TezXSVHHxsA8FTOcX9Ot7SIb/iFBSx57o49FZrcrVq4ZqbQDC47SGPo5s/XtDZYcXgORjy8SL4fZ/Dk/GqIPjdVS87E7cSr+/KiYsYqwDR2qNv1GqcA7rPZze0caEv3Yhou5xd9ZqpvXqowCuwZRyrMMo06Tyni5xtkysk+NpbPgavmdAzNiyK3Yo7O+KwcULDzeNUuBp/X87/keWzHjvPD+G+f3rB5LDZLQVjwB8mh+F755zBh0UkoD3r0DcYwpo+gpAztuVnspVH1q//0qhJUSD/SKX1vWeUXf+s7Po/ZHsEKJS/gI+OsVzOCGX33NJzUv9T4ipAocVOsPa2OoNQfxYu+Vlnf9htqh0GKaSV6ipKTRqkW0DLxWuPjc8SS/qyzfHss4YPS8Y=
  bucket: danielwiltshire.co.uk
  region: eu-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: dist
  on:
    repo: danwiltshire/portfolio-frontend